### ISSUE TITLE
Possible improvement: Group emoticons, make selection easier

### ISSUE THREAD

**Issue by l3u** [dslul/openboard#134] opened 2020-08-22 07:59 UTC
First of all: Thanks for your great work, it looks very promising (esp. as a maybe better alternative to AnySoftKeyboard)!

Maybe, the emoticon selection could be a bit clearer. Considering the first category, the "normal" ones are okay as-is, but when one reaches the human-like ones, all variants (skin colors) are listed, so that one page contains only a few ones.

What about grouping those, so that the yellow version is shown with an indicator that there are more variants, and the skin color ones are displayed as a popup? That would be, imo, a lot clearer and more overseeable.

Maybe, you could also consider to introduce another category page for the humanoid emoticons, next to the "smiley" one, also to ease selection.

Also, maybe you want to add more "normal" "text" smilies or – ideally – add the possibility to define custom ones (which would be a really outstanding feature!).

Just suggestions :-) Keep on rocking!

**Comment by dslul** [comment] 2020-09-08 06:43
Thanks. There is a plan to overhaul the emoji keyboard. I'll close this as duplicate of #6.

**Closed by dslul** 2020-09-08 06:43 UTC
