### ISSUE TITLE
Function suggestions

### ISSUE THREAD

**Issue by Pantyhose-X** [dslul/openboard#307] opened 2021-02-23 04:54 UTC
* 1.clipboard manager  Don't limit the quantity
* 2.Hope to support [Mozilla's Text-to-Speech](https://github.com/mozilla/TTS) Always speak typed keys Speak phonetic letters Phonetic letters are spoken when long pressing on keyboard keys and navigating by character.Applied to language learning. Pronunciation correction
* example，https://www.youtube.com/watch?v=YPBn6D6pf78&feature=youtu.be&t=213

**Comment by dslul** [comment] 2021-05-12 07:07
duplicate of #235

**Closed by dslul** 2021-05-12 07:07 UTC
