### ISSUE TITLE
Please add Japanese support.

### ISSUE THREAD

**Issue by linusrg1** [dslul/openboard#239] opened 2020-12-08 13:18 UTC
I need Japanese support for my Japanese learning could you please add it. Even after adding a Japanese language pack from fdroid I do not see Japanese as an option anywhere.

**Comment by kineita** [comment] 2021-01-06 02:50
+1 for Japanese

**Comment by DaringRaspberry** [comment] 2021-05-16 19:53
+1

**Comment by jnnkB** [comment] 2021-06-12 08:05
Closing this issue since it is a duplicate of #192 and #103.

**Closed by jnnkB** 2021-06-12 08:05 UTC
Labels: layout
