### ISSUE TITLE
Search function for emojis

### ISSUE THREAD

**Issue by postretrofuture** [dslul/openboard#86] opened 2020-04-10 10:58 UTC
Whilst the emoji skin color consolidation will save a lot of time, it would be real handy if we could have a search function either like ASK does by prefixing with a colon or by adding to the suggestion bar as in google(?) keyboard (preferred).

Thanks

**Comment by sharpsan** [comment] 2020-04-17 03:11
This is a much needed feature.

**Comment by roshavagarga** [comment] 2020-04-18 10:26
Wouldn't this be possible by creating per-language files like this one and using them when creating the dict files? https://github.com/dslul/openboard/blob/master/dictionaries/en_emoji.combined.gz

**Comment by GLLM** [comment] 2020-05-12 13:45
I'm very much in favor of the emoji search with a colon -->   :

**Comment by resynth1943** [comment] 2020-05-22 23:27
I would *love* this feature. Emoji search is one of the things GBoard does best, and not many FOSS keyboards have this, if any. It would be nice to see a FOSS keyboard support this.

**Comment by EgidioCaprino** [comment] 2020-07-10 14:22
I would appreciate this feature. Without it I ended up using Emoji only with applications that have their own search functionality, like Telegram.

**Comment by kojid0** [comment] 2020-09-02 10:22
duplicate of #35

**Comment by dslul** [comment] 2020-09-07 12:48
Closing as duplicate.

**Closed by dslul** 2020-09-07 12:48 UTC
