### ISSUE TITLE
Multilingual typing

### ISSUE THREAD

**Issue by davidj77** [dslul/openboard#428] opened 2021-09-04 13:35 UTC
Hi, can you add to OpenBoard a feature that let us get suggestions in more than a language without switching between keyboards?
For example when we are writing in Spanish but need to write only a word in English, then it appears the suggestion for the word we need write in English without change to English keyboard or save the word to Spanish dictionary for use it again when need it.
![20210904_083227](https://user-images.githubusercontent.com/71226185/132096208-0aacc004-2ddb-4554-81cb-55dfe310e232.png)
In the example I'm using Spanish layout but I need a word in English and I can write I without change to English keyboard.
Thanks in advance.

**Comment by mtnyzr** [comment] 2021-09-04 18:57
Will be good like SwiftKey

**Comment by jnnkB** [comment] 2021-09-08 15:15
Duplicate of https://github.com/dslul/openboard/issues/167 and/or https://github.com/dslul/openboard/issues/7

**Closed by jnnkB** 2021-09-08 15:15 UTC
Labels: enhancement
