### ISSUE TITLE
BUG: special characters do not show

### ISSUE THREAD

**Issue by protomo** [dslul/openboard#99] opened 2020-05-08 06:01 UTC
special characters show up only when you use phone's default language (english), and they do not show up on other languages even on english (azerty), is this a bug or it is meant to be like this? im confused.

**Comment by sandsturm** [comment] 2020-05-08 13:46
Can you please provide an example with screenshots and which characters are not displayed in which other languages? I cannot reproduce this problem.

**Comment by protomo** [comment] 2020-05-08 20:51
> Can you please provide an example with screenshots and which characters are not displayed in which other languages? I cannot reproduce this problem.

i have the screenshots but i couldn't figure out how to upload them, i'm new to github sorry, how can i upload them?

**Comment by protomo** [comment] 2020-05-08 22:39
never mind i found out how, these are the screenshots from "French(azerty)", even english(azerty) have the same bug.

<blockquote class="imgur-embed-pub" lang="en" data-id="a/Ho8vogD"><a href="//imgur.com/a/Ho8vogD"></a></blockquote><script async src="//s.imgur.com/min/embed.js" charset="utf-8"></script>

**Comment by sandsturm** [comment] 2020-05-09 17:45
Okay, understood. This is the same bug as #77. Can you please read #77 and post here, what kind of special characters you would expect and for which language(s)?

**Comment by protomo** [comment] 2020-05-12 05:57
looking at the thread you reffered to shows that more people have the same problem as i do, and about special characters, the same characters as english are okey. thank you for your responses this shows how great dev you are.

**Comment by protomo** [comment] 2020-05-12 05:57
looking at the thread you reffered to shows that more people have the same problem as i do, and about special characters, the same characters as english are okey. thank you for your responses this shows how great dev you are.

**Comment by sandsturm** [comment] 2020-05-12 07:00
Thank you very much. It is just xml configuration. I have just copied over the definitions from the qwerty keyboard. Would this match your requirement?

![image](https://user-images.githubusercontent.com/2701346/81648467-08c93800-942f-11ea-8fa2-2b87507d79a4.png)

**Comment by protomo** [comment] 2020-05-15 06:45
yes perfect ! just some random question if i may, can the "m" letter on azerty keyboards be in the same location as the "m" on qwerty? my hands are used to it in that location cause i used lg keyboard before yours, implementing this as an option maybe can help a lot, specially with the special characters fix + a separated number row 😍 makes it the perfect keyboard. Thank you again dev already recommended you to bunch of my friends.

**Comment by sandsturm** [comment] 2020-05-15 06:52
Created pull request #100

**Comment by sandsturm** [comment] 2020-05-15 06:54
Moving the "m" letter. Yes, that is an easy task in the configuration files but it is a good practice to keep the layout to the standard 😉

**Comment by m-sameer** [comment] 2020-06-13 18:25
Close this issue too

**Closed** 2020-09-07 12:44 UTC
