### ISSUE TITLE
feature request : multiple languages correction on one keyboard

### ISSUE THREAD

**Issue by ThomasTraineau** [dslul/openboard#259] opened 2021-01-06 14:53 UTC
On gboard, you can select multiple languages with the same layout and when you type words, the autocorrection works for both languages at the same time. This is vzry convenient when you often switch languages, so you don't have to switch keyboards

**Comment by jnnkB** [comment] 2021-01-07 10:47
Isn't this a duplicate of #167 and/or #7?

**Closed** 2021-03-18 10:45 UTC
