### ISSUE TITLE
Feature Request: Swipe to text / Glide to text

### ISSUE THREAD

**Issue by ThoLorax503** [dslul/openboard#270] opened 2021-01-15 12:59 UTC
Thank you, Team, for the time and energy put into creating a fully functional interface like this. I am new to the whole AOSP/FOSS world as I am preparing to migrate from years of Apple shackles. One helpful thing Apple recently adopted is the swipe-to-text feature, which I believe they emulated from Google. You just drag your finger across the keyboard and it inputs the word you are trying to type, and shows a list of suggested words if they did not input what you wanted. I was curious if this is something that could be implemented in the future?

**Comment by stephen304** [comment] 2021-01-16 17:29
This is what I miss most from gboard. I simply can't type quickly and accurately for basic communications without it.

**Comment by sirsleon** [comment] 2021-01-18 11:24
I agree, this is probably the only thing stopping me from fully jumping over.

**Comment by soulmist7** [comment] 2021-01-27 03:20
I came here to say I was so hoping to go with your keyboard - but unable to swap over without swipe!

**Comment by zpangwin** [comment] 2021-01-30 18:57
> 
> 
> I agree, this is probably the only thing stopping me from fully jumping over.

Same here. Was just testing this out and it is a very excellent keyboard... unfortunately, I've come to rely heavily on swipe-to-text and am having a hard time typing as efficiently without it.

It seems there is some overlap [here](https://github.com/dslul/openboard/issues/3) related to this discussion, but I hesitate to call this a duplicate issue as the older issue discussion seems to have shifted course to "Moving the cursor by swiping on space would also be very nice." and unsupported workarounds for building your own hacked copy of OB rather than staying focused on "swipe to text" integration in the official code base.

**Comment by jnnkB** [comment] 2021-03-16 16:48
duplicate of #3

**Closed** 2021-03-18 10:50 UTC
