### ISSUE TITLE
Multiple dictionaries at once

### ISSUE THREAD

**Issue by Wilker-a** [dslul/openboard#101] opened 2020-05-15 13:32 UTC
because i type in more than one language, sometimes even in the same section, i would like to have the word suggestions also suggesting the different languages and adapting as i type, because i don't want to be changing the language all the time.

thank you for making this \^w\^

**Comment by TheCrowned** [comment] 2020-05-24 08:52
This would be super cool, albeit difficult to implement I guess

**Comment by damrath** [comment] 2020-06-06 10:01
You could probably create a custom dictionary that contains words from both languages. That would solve spell-checking, but i reckon suggestions would be kind of inaccurate. 

In the app i saw the "personal dictionary" option and kind of expected it to allow me to select multiple default dictionaries for my "personal" dictionary in addition to adding my own words.

So unless a feature is developed for this use-case, i think the quickest solution would be to create a custom dictionary as referenced in the README.

**Comment by dslul** [comment] 2020-09-07 18:16
Duplicate of #7.

**Closed by dslul** 2020-09-07 18:16 UTC
