### ISSUE TITLE
would it be possible to integrate a clipboard?

### ISSUE THREAD

**Issue by murph2495** [dslul/openboard#443] opened 2021-10-01 13:21 UTC
Hi guys. Do you think it would be possible to add a clipboard to the keyboard? That would be great. I think that is the only thing the keyboard lacks to be a solid option compared to the other keyboards like gboard o swiftkey

**Comment by jnnkB** [comment] 2021-10-01 13:40
Duplicate of #16 #60. If you don't agree simply comment.

**Closed by jnnkB** 2021-10-01 13:40 UTC
Labels: enhancement
