### ISSUE TITLE
English (United Kingdom) isn't using British English

### ISSUE THREAD

**Issue by fohfuu** [dslul/openboard#484] opened 2022-01-16 01:46 UTC
**Describe the bug**
Words that are spelled differently in British English, like "realise" or "colour", are not suggested and are marked as misspellings. American English spellings are suggested instead, like "realize" and "color".

**To Reproduce**
Set OpenBoard language to English (United Kingdom).
Go to language settings (different between OS versions).
Language & Input > Input Assistance > Spell checker > Default spell checker, set to OpenBoard Spell Checker.
In any text box which allows suggestions, type a word that has different spellings in UK English and US English.

**Expected behavior**
The English (UK) spelling is suggested.

**Screenshots**

**Smartphone (please complete the following information):**
 - Nokia 8
 - Android 9

**Additional context**
I don't understand the instructions for making a new dictionary at all so I can't make one for you.

If you decide this will not be fixed, I understand. If that is the case, please remove the dictionary from the app altogether, as it is not functional.

**Comment by jnnkB** [comment] 2022-01-16 16:24
Duplicate of #439

**Closed by jnnkB** 2022-01-16 16:24 UTC
