### ISSUE TITLE
[Feature Request for App-Stores] Add Changelog for most Recent Version.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dslul/openboard#182] opened 2020-10-11 08:39 UTC
In both F-Droid and the Play Store, there's appears to be a functionality to describe the most recent changes. I suggest using this option, as it's really interesting to actually know WHY one would want to update a certain app. Also it's exciting to update an app, knowing there's some cool new functionality.
(Also, this might encourage people to try new features... which could mean more/better feedback here on GitHub.)

If it's not 100% clear what I'm talking about, just visit the "Etar Calendar"-app in either app-store and compare it to the OpenBoard-page.

**Comment by dslul** [comment] 2020-10-14 11:45
I am aware that F-Droid is not showing the changelog (I think because it's too long), but it should be there on the Play Store. At least I can see it.

**Comment by Glitchy-Tozier** [comment] 2020-10-14 13:41
Oh, yeah, youre right... Apparently i missed it in the Play Store.

Regarding F-Droid: I think, there must be a different reason. For example, this app https://f-droid.org/packages/com.machiav3lli.backup (OAndBackupX) seems to habe a longer changelog and it's still displayed.
(If I'm correct, i counted 9 instead of 8 different changes and its sentences seemed slightly longer)

**Comment by jnnkB** [comment] 2021-03-16 13:52
Since its working in the Play Store i think this is a duplicate of https://github.com/dslul/openboard/issues/171

**Closed** 2021-05-28 22:08 UTC
