### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by Freespeech-zone** [dslul/openboard#54] opened 2020-02-03 19:43 UTC
Would be nice to have a swtich or an option to turn on incognito mode.
Apps like signal and telegram use incognito mode keyboard for their chats windows but it doesn't turn on with this keyboard.

**Comment by Offerel** [comment] 2020-05-15 18:23
The keyboard should switch automatically to incognito mode, if the app requests this. At least this is what Firefox does.

**Comment by Freespeech-zone** [comment] 2020-05-15 18:33
Emoji option disappears on twitter app.

**Comment by kojid0** [comment] 2020-09-02 08:31
There's still a bug with incognito mode, so using it would currently lead to much disappointment. No word suggestions/auto correct available at the moment, see #12. Hope this will be fixed soon, very annoying bug.

**Comment by dslul** [comment] 2020-09-07 10:50
Fixed in a6d7e2d3ac87b6335d9f118ef750e9c1cca7c97b. Closing as duplicate of #12

**Closed by dslul** 2020-09-07 10:50 UTC

**Comment by jwsp1** [comment] 2020-09-19 08:29
This does not work for me in latest version. I typed a sentence multiple times in a Telegram Secret Chat (which asks openboard to be incognito) but then the sentence is being suggested in another chat. Being incognito should stop openboard to learn words and next-word-predictions.
Swiftkey works as intended. It even switches keyboard theme to dark mode whenever it is (automatically) in incognito mode.
Anysoftkeyboard works as well (you can see it by the "crossed-eye"-icon in the bottom right hand corner. Visible feedback should be implemented in openboard as well, e.g. by the Anysoftkeyboard approach.
Please reopen @dslul. Many thanks!!

**Comment by dslul** [comment] 2020-09-23 09:29
> This does not work for me in latest version. I typed a sentence multiple times in a Telegram Secret Chat (which asks openboard to be incognito) but then the sentence is being suggested in another chat. Being incognito should display suggestions, but stop openboard to learn words and next-word-predictions.
> Swiftkey works as intended. It even switches keyboard theme to dark mode whenever it is (automatically) in incognito mode.
> Anysoftkeyboard works as well (you can see it by the "crossed-eye"-icon in the bottom right hand corner. Visible feedback should be implemented in openboard as well, e.g. by the Anysoftkeyboard approach. A clickable icon, or key hint via long-press "ENTER" or "," could also help users to quickly switch between normal and incognito mode.
> Please reopen @dslul. Many thanks!!

@jwsp1 are you sure you didn't type that sentence elsewhere? I cannot reproduce this issue with telegram secret chats. I was already planning to add an incognito icon on the left part of the suggestion strip.

**Comment by jwsp1** [comment] 2020-09-25 17:38
> > This does not work for me in latest version. I typed a sentence multiple times in a Telegram Secret Chat (which asks openboard to be incognito) but then the sentence is being suggested in another chat. Being incognito should display suggestions, but stop openboard to learn words and next-word-predictions.
> > Swiftkey works as intended. It even switches keyboard theme to dark mode whenever it is (automatically) in incognito mode.
> > Anysoftkeyboard works as well (you can see it by the "crossed-eye"-icon in the bottom right hand corner. Visible feedback should be implemented in openboard as well, e.g. by the Anysoftkeyboard approach. A clickable icon, or key hint via long-press "ENTER" or "," could also help users to quickly switch between normal and incognito mode.
> > Please reopen @dslul. Many thanks!!
> 
> @jwsp1 are you sure you didn't type that sentence elsewhere? I cannot reproduce this issue with telegram secret chats. I was already planning to add an incognito icon on the left part of the suggestion strip.

I will recheck when v1.4 is available in F-Droid. Do you know why it's >2 weeks late?

**Comment by jwsp1** [comment] 2020-09-25 20:32
You mean something like this? I added a clipboard paste icon on the right as well.
![openboard_suggestion](https://user-images.githubusercontent.com/66554665/94313253-ace6f200-ff7e-11ea-8a35-4ec1bc803542.png)

**Comment by dslul** [comment] 2020-09-26 06:42
> You mean something like this? I added a clipboard paste icon on the right as well.
> ![openboard_suggestion](https://user-images.githubusercontent.com/66554665/94313253-ace6f200-ff7e-11ea-8a35-4ec1bc803542.png)

Yes!

**Comment by jwsp1** [comment] 2020-09-26 10:34
Thanks, I will let you know if the bug is present when F-Droid pushes the new version. I don't want to lose my word suggestions by installing the apk from github...
