### ISSUE TITLE
[Feature request] Seperate number row

### ISSUE THREAD

**Issue by p4ddywhack** [dslul/openboard#121] opened 2020-07-16 22:58 UTC
Could you add an option to have the number row seperately instead of having to long-tap to get to them?
Thanks

**Comment by mfortini** [comment] 2020-07-31 10:46
Duplicate of #98

**Comment by nomad-skateboarding** [comment] 2020-07-31 12:56
> Could you add an option to have the number row seperately instead of having to long-tap to get to them?
> Thanks

Already asked

**Comment by kojid0** [comment] 2020-09-02 10:23
duplicate of #21

**Closed** 2020-09-07 12:45 UTC
