### ISSUE TITLE
Symbols on long press

### ISSUE THREAD

**Issue by Zayon** [dslul/openboard#77] opened 2020-03-10 12:54 UTC
On the app screenshots we see that symbols are accessible through long press on letters

![screenshot from google play](https://lh3.googleusercontent.com/C_4AStf9NJnXz8fEKLppDuPCJouWBRRj7U8hPMOf-QSTqipE8x1CaWyJ8Yibf_oghMM3=w1674-h997)

I search all the options but I can't find the way to activate this.

![Screenshot_20200310-134856__01](https://user-images.githubusercontent.com/3958468/76314091-7691a000-62d6-11ea-8703-c0288a3159e9.jpg)

**Comment by OpenWarp** [comment] 2020-03-15 10:23
This is weird, as mine is working exactly as it should, with any supported layout. In fact, I disabled all other keyboards in favour of OpenBoard. Would you please provide more detail, as I am unable to reproduce this issue on two different phones using F-Droid version.

**Comment by Zayon** [comment] 2020-03-15 22:12
OK I did some testing and it only occurs with the French layout.

It works with:
* French (Canada)
* German
* Spanish
* English (us and UK)

**Comment by sandsturm** [comment] 2020-04-05 20:40
I did some quick checks in the source code. French uses the azertz XML definitions which are lacking the additionalMoreKeys. German for example uses the qwertz XML definitions.

Excerpt from rowkeys_qwertz2_left5 (de locale):
<Key
        latin:keySpec="f"
        latin:keyHintLabel="%"
        latin:additionalMoreKeys="%" />

and an excerpt from the rowkeys_awerty2_left5 (fr locale):
<Key
        latin:keySpec="f" />

What would you expect? I can add it to the xml defintions and can commit the change and ask for a merge.

Best regards,
Martin Sand

**Comment by sandsturm** [comment] 2020-05-12 07:54
I just did an update of #99. The user mentioned to have the same special characters as for qwerty. This is how it looks like.

![image](https://user-images.githubusercontent.com/2701346/81648467-08c93800-942f-11ea-8fa2-2b87507d79a4.png)

**Comment by sandsturm** [comment] 2020-05-15 06:52
Created pull request #100

**Comment by m-sameer** [comment] 2020-06-13 18:24
Close this issue.

**Comment by dslul** [comment] 2020-09-07 13:21
@sandsturm Thanks!

**Closed by dslul** 2020-09-07 13:21 UTC
