### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by b3wii** [dslul/openboard#193] opened 2020-10-17 23:23 UTC
Thank you for this great app!!

Feature requests:
 - When long press on enter show copy and paste buttons.
 - When on emoji screen and you press the back button the keyboard should not close but go back to default state (open and letters showing).
 - not really important but it would be nice to change the emojis

**Comment by Oymate** [comment] 2020-11-22 16:20
The first two are probably handled by the system and not the app

**Comment by b3wii** [comment] 2021-03-18 16:14
> The first two are probably handled by the system and not the app

Yes i know that the system also handles this but its sometimes comes in handy if you can copy and paste via keyboard and since there is already a long-press action on the enter button i figured that it would be an easy task to implement/use the system copy&paste function like Chrooma does it.

Second point: the backbutton should be intercepted at this point and return to initial keyboard layout and not close the keyboard.

**Comment by jnnkB** [comment] 2021-05-28 21:50
Regarding your first suggestion: I think it is a duplicate of https://github.com/dslul/openboard/issues/60. 

What do you mean by changing the emojis?

**Comment by Oymate** [comment] 2021-05-29 14:13
Like the third one? https://github.com/dslul/openboard/issues/172

**Comment by jnnkB** [comment] 2021-05-29 14:22
I think its currently simply using the system font emojis which has the advantage that the emoji looks the same in the keyboard and in all apps that don't serve their own emojis.

**Comment by b3wii** [comment] 2021-06-01 15:38
> Like the third one? #172

Yes, but just nice to have and not really important. Copy&Paste on the other hand would be very useful because there are my apps that are buggy. I would prefer them showing up on enter long-press since no other button or extra row would be needed.

**Comment by jnnkB** [comment] 2021-06-01 15:44
Ok. So it seems like your first and third point are already in some other issues. Would you mind starting a new issue with your second point and closing this one? That could help to have an better overview on the issues.

**Comment by b3wii** [comment] 2021-06-01 15:46
> Ok. So it seems like your first and third point are already in some other issues. Would you mind starting a new issue with your second point and closing this one? That could help to have an better overview on the issues.

Yes sure, i will ater.

**Comment by jnnkB** [comment] 2021-06-01 15:47
Perfekt. Thanks a lot

**Closed** 2021-06-18 20:14 UTC
Labels: enhancement
