### ISSUE TITLE
Fast Swiping doesn't always work.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [dslul/openboard#65] opened 2020-02-12 21:15 UTC
There are two functionalities that seem to use this swiping-method: "Space-Bar-Trackpad" and "Delete-Swipe".

Both sometimes behave weirdly if you swipe too quickly. Sometimes nothing changes at all, sometimes the cursor snaps back after your finger leaves the screen (often just a few spaces).

**Comment by dslul** [comment] 2020-02-13 07:20
I noticed that this only happens in some fields (i.e. during web browsing with firefox focus) but not on others. Do you experience this behaviour on all apps?

**Comment by jwsp1** [comment] 2020-02-13 08:14
Maybe this is related with the strange behavior in some fields mentioned in #12

**Comment by Glitchy-Tozier** [comment] 2020-02-13 08:30
@dslul Firefox Focus (or FF Klar, the german version) is definitely one place where I've noticed this, exactly.
However, I feel like it also sometimes happens in other places, for example in Whatsapp... Although it seems to be less extreme there.

**Comment by Pentaphon** [comment] 2020-03-04 13:59
@dslul Is Openboard built from the latest AOSP Keyboard code? Maybe it's been fixed in a more recent version?

**Comment by Glitchy-Tozier** [comment] 2020-05-26 18:40
A place where this seems to happen about 100% of the time is the Collins Dictionary WebApp. Just in case you want to mess around with it or see, whether it's the same for you.

Also, it seems like this is not just **fast** swiping. It's *swiping in general*.

One thing that happens a lot is when I swipe (and the cursor bugs around) and then start deleting, somewhere while deleting the cursor just jumps to a completely new place within the phrase and makes me delete the wrong thing.

**Comment by dslul** [comment] 2020-09-04 17:58
@Glitchy-Tozier I changed the swipe behaviour, which seems to work better. Simple keyboard has the same issue because I took the code from there.

**Comment by Pentaphon** [comment] 2020-09-05 02:20
> Simple keyboard has the same issue because I took the code from there.

Is that derived from the most up-to-date AOSP keyboard version or is there something more mature out there?

**Comment by dslul** [comment] 2020-09-05 06:54
> Is that derived from the most up-to-date AOSP keyboard version or is there something more mature out there?

AOSP development has been dead for many years, otherwise there would be no need to fork it. Google continued its development in the current gboard.

**Comment by Glitchy-Tozier** [comment] 2020-09-05 09:04
> @Glitchy-Tozier I changed the swipe behaviour, which seems to work better. Simple keyboard has the same issue because I took the code from there.

So the next update should remove the issue?

**Comment by dslul** [comment] 2020-09-05 10:42
> So the next update should remove the issue?

Yes, as soon as the number row pull request is complete, I'll push the update.

**Comment by dslul** [comment] 2020-09-08 11:59
I'll close this as it's a duplicate of #58.

**Closed by dslul** 2020-09-08 11:59 UTC
