### ISSUE TITLE
Feature request: Make a word start with a capital letter from the end of the word by shift key

### ISSUE THREAD

**Issue by utzer** [dslul/openboard#254] opened 2021-01-03 10:19 UTC
Not sure how the write that topic in a shorter way, but what I would like to see as a feature is the possibility to change the first letter of a word to a capital letter by pressing shift while at the end. 
This could be implemented as following, when a word is typed and the cursor is at the end of the typed word and then shift is pressed followed by space it would finish the word and switch the first letter to capital. 

This would be very helpful in languages where many words are capitalized and you can easily forget to type shift in the beginning. Sometimes autocorrect does not catch this cases due to grammatical  specialities.

**Comment by slaecker** [comment] 2021-01-04 08:40
I'd appreciate this as well. In German the same words need to start with a capital letter bases on the grammatical context.
You can find this feature on Swiftkey (my former favorite keyboard until bought by Microsoft) and it saves so much time not having to go to the start of the word to change the first letter.

You type a word, autocorrect suggests the correct but lowercase word, you tap SHIFT and the suggestions change to capital first letter.

**Comment by ben-utzer** [comment] 2021-01-04 09:01
Exactly that.

**Comment by jnnkB** [comment] 2021-03-16 14:07
Is this a duplicate of https://github.com/dslul/openboard/issues/141?

**Closed** 2021-03-18 10:48 UTC
