### ISSUE TITLE
reduction of emojis

### ISSUE THREAD

**Issue by Bondarz** [dslul/openboard#51] opened 2020-02-02 19:29 UTC
Hello,

can the number of emojis be reduced?
example people with skin colours, here you have to scroll for a long time. is a simple tap on the figure enough to choose the colour?

thanks :)

**Comment by ChildishGiant** [comment] 2020-02-02 20:21
Duplicate of #6

**Comment by dslul** [comment] 2020-02-03 07:21
I was planning to replace/overhaul the emoji keyboard entirely, with something that resembles the telegram one. We can keep the discussion on the other thread. I'll close this one.

**Closed by dslul** 2020-02-03 07:21 UTC
