### ISSUE TITLE
*Turkish-Q* layout

### ISSUE THREAD

**Issue by ekiniko12** [dslul/openboard#388] opened 2021-06-16 08:48 UTC
Add here references to the layout (links or screenshots).
![index](https://user-images.githubusercontent.com/85990602/122188514-b3b0ee80-ce98-11eb-92b1-46bc51912c5d.jpg)

**Comment by jnnkB** [comment] 2021-06-18 12:07
duplicate of #309

**Closed by jnnkB** 2021-06-18 12:07 UTC
Labels: layout
