### ISSUE TITLE
Language request: Chinese, Japanese

### ISSUE THREAD

**Issue by Manothave** [dslul/openboard#200] opened 2020-10-22 18:00 UTC
Language request: Chinese, Japanese

**Comment by modestderp** [comment] 2020-12-22 05:54
+1 for Chinese support

Personally I specifically need Traditional Chinese support on Openboard with **Hanyu Pinyin** input
If Traditional Chinese works, then I can ditch GBoard completely
Switching between Openboard and Trime when typing is too cumbersome for prolonged use...

**Comment by fishman** [comment] 2021-01-15 09:28
I have the same issue, what is necessary to add this?

**Comment by jnnkB** [comment] 2021-03-16 12:56
Duplicate of #192

**Closed** 2021-03-18 10:44 UTC
