### ISSUE TITLE
Japanese support

### ISSUE THREAD

**Issue by lucascamara-drk** [dslul/openboard#385] opened 2021-06-12 06:52 UTC
I love your keyboard, it is exactly what I've been looking for. However, nowadays my languages needs are Portuguese (native), English (for academic purposes) and Japanese, also my subject of study.

So please, if you could include a romaji or hiragana japanese keyabord would be great.

**Comment by jnnkB** [comment] 2021-06-12 08:03
This probably is a duplicate of #192, #103 and #239. Do you @lucascamara-drk agree? If thats right I would like to close this issue.

**Comment by lucascamara-drk** [comment] 2021-06-12 13:35
> This probably is a duplicate of #192, #103 and #239. Do you @lucascamara-drk agree? If thats right I would like to close this issue.

If it is duplictate, you can closr this one. Is the team working on it?

**Comment by jnnkB** [comment] 2021-06-12 15:50
I don't think anyone is working on it currently. @dslul wrote this in #103:

> I definitely cannot do it by myself, it's better if it's done by someone who uses these layouts. [...] The layouts are in res/xml

I think everybody would appreciate a PR with a Japanese layout. So feel free to do so.

**Closed by jnnkB** 2021-06-12 15:50 UTC
Labels: layout
