### ISSUE TITLE
Japanese and Korean keyboard support

### ISSUE THREAD

**Issue by FBIAgent05** [dslul/openboard#398] opened 2021-07-01 14:32 UTC
**Is your feature request related to a problem? Please describe.**
Yes, I use type in Japanese and Korean sometimes, and I don't see an open-source keyboard for it

**Describe the solution you'd like**
Implement a Japanese and Korean keyboard

**Describe alternatives you've considered**
Gboard, but it's not open source, i do not trust google in a privacy perspective

**Additional context**
![Screenshot_20210701_222219.jpg](https://user-images.githubusercontent.com/74946397/124141578-1bcc1b00-dabc-11eb-88f6-a975c3df77fa.jpg)
![Screenshot_20210701_223129.jpg](https://user-images.githubusercontent.com/74946397/124141585-1e2e7500-dabc-11eb-9838-344bfa96fcc9.jpg)

**Comment by jnnkB** [comment] 2021-07-01 16:14
This is a duplicate of #103 and #24

**Closed by jnnkB** 2021-07-01 16:14 UTC
Labels: enhancement
