### ISSUE TITLE
Feature request: ctrl button 

### ISSUE THREAD

**Issue by nahuhh** [dslul/openboard#272] opened 2021-01-18 16:51 UTC
Use case 
Ctrl + a,v,c,x,z,y etc for select all etc 
[20210118_112542.jpg](https://user-images.githubusercontent.com/50635951/104943165-51a09b80-5983-11eb-8633-7bc28a56e2c8.jpg)

**Comment by mainmachine** [comment] 2021-02-18 18:39
Also for ssh commands, for instance ctrl+d to exit session, ctrl+r for bash history, etc.

Lack of this key means I cannot use openboard as a primary keyboard.

**Comment by jnnkB** [comment] 2021-03-16 14:17
Is this a duplicate of https://github.com/dslul/openboard/issues/84 ?

**Closed** 2021-03-18 10:48 UTC
