### ISSUE TITLE
[Feature request] Adding swype feature

### ISSUE THREAD

**Issue by Christian-Git01** [dslul/openboard#117] opened 2020-07-01 15:33 UTC
Are there any plans on adding swype feature? Some information about this topic:
[jupyter notebook about gesture typing](https://nbviewer.jupyter.org/url/norvig.com/ipython/Gesture%20Typing.ipynb)

[paper by google](https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43461.pdf)

**Comment by dslul** [comment] 2020-09-07 17:55
Yes, but it's not a simple task for a single person. I'll close this as it's a duplicate of #3 .

**Closed by dslul** 2020-09-07 17:55 UTC
