### ISSUE TITLE
Enable to run on boot.

### ISSUE THREAD

**Issue by karnotcycle** [dslul/openboard#354] opened 2021-05-10 05:26 UTC
**Is your feature request related to a problem? Please describe.**

Yes, The keyboard doesn't work until unlocked after boot. Simple keyboard on the other hand runs on boot without unlocking required.

**Describe the solution you'd like**

Honestly this one option is keeping me from using it full fledged.

**Describe alternatives you've considered**
Using simple keyboard just for unlocking.

They are even happy for you to copy the feature : here's a reply from them - "File an issue for OpenBoard. They are welcome to copy daae07b."

**Comment by jnnkB** [comment] 2021-05-10 11:38
I think this is a duplicate of https://github.com/dslul/openboard/issues/75 and already fixed in https://github.com/dslul/openboard/pull/346

**Comment by TheCrowned** [comment] 2021-05-10 19:07
> Does it mean It will get fixed in the next release?
Yes

**Closed** 2021-05-12 06:58 UTC
Labels: enhancement
