### ISSUE TITLE
Force autocorrect/text correction bar to always on?

### ISSUE THREAD

**Issue by S-360** [dslul/openboard#132] opened 2020-08-15 11:55 UTC
The autocorrect/text correction bar doesn't appear in certain apps or text dialog boxes. Is it possible to have it always on regarless of where text is being entered?

The Samsung keyboard is able to do this and text correction is on all the time in all apps.

Device: Samsung A50

**Comment by dslul** [comment] 2020-09-07 10:54
Fixed a6d7e2d3ac87b6335d9f118ef750e9c1cca7c97b. Duplicate of #12

**Closed by dslul** 2020-09-07 10:54 UTC
