### ISSUE TITLE
toggle to remove spacebar long press to change language

### ISSUE THREAD

**Issue by aha999** [dslul/openboard#478] opened 2021-12-24 10:12 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when i accidentally long press spacebar for long enough so language preferences open up all the time. i also use the spacebar for sliding through letters, so whenever i make a mistake of long pressing it long enough, it opens language preferences and in the quick typing i accidentally change languages or even change keyboards because they're next to each other... that's extremely annoying because then i have to reverse that settings every time.

**Describe the solution you'd like**
please add an option to turn off language switching if long pressing spacebar, so it would stay only in the button, that is already used for emoji and settings and locale if long pressing it left of the spacebar.

**Comment by jnnkB** [comment] 2022-01-08 18:56
duplicate of #455

**Closed by jnnkB** 2022-01-08 18:56 UTC
Labels: enhancement
