### ISSUE TITLE
Emoji Suggestions

### ISSUE THREAD

**Issue by Blquinn** [dslul/openboard#775] opened 2023-03-28 14:17 UTC
On iOS the keyboard will suggest emojis for you based on the phrase that you're currently typing.

If I type "angry" (up to 3) emojis will pop up in the right hand suggestion box. It is a subtly excellent feature.

I would be open to implementing this myself if someone could give me some direction!

**Comment by jnnkB** [comment] 2023-04-15 09:53
duplicate of #197, addressed in #749

**Closed as not planned by jnnkB** 2023-04-15 09:53 UTC
Labels: enhancement
