### ISSUE TITLE
Redundancy of the numbers.

### ISSUE THREAD

**Issue by hiru12** [dslul/openboard#228] opened 2020-11-22 17:54 UTC
The numbers on Long pressed QWERTY are still there even though I enabled the "Always Show Number Row".
![Screenshot_2020_1123_015219](https://user-images.githubusercontent.com/74873448/99911365-d201a200-2d2e-11eb-9b31-e9a02c45de6d.png)

**Comment by kojid0** [comment] 2020-11-22 18:18
Have you checked existing issues?
Duplicate of #189.

**Closed** 2021-03-18 10:46 UTC
