### ISSUE TITLE
Release notes for Github Releases

### ISSUE THREAD

**Issue by aha999** [dslul/openboard#357] opened 2021-05-12 12:35 UTC
**Is your feature request related to a problem? Please describe.**
Currently, i can't find release notes for new versions not in fdroid or in github, so i can see if it's worth updating based on my needs.

**Describe the solution you'd like**
Add release notes for new versions of the app.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by jnnkB** [comment] 2021-05-13 07:01
The changelog is located here https://github.com/dslul/openboard/blob/13c548c79f4a3271b46bb54395dd9d5123fe28b6/fastlane/metadata/android/en-US/changelogs/1.4.3.txt

**Comment by aha999** [comment] 2021-05-13 12:15
Please add Changelog info to F-Droid like this if possible [Keepass](https://f-droid.org/en/packages/com.kunzisoft.keepass.libre/):

![slika](https://user-images.githubusercontent.com/50620416/118124001-491e1600-b3f5-11eb-8b4a-65edb2c8c6e5.png)

**Comment by jnnkB** [comment] 2021-05-29 12:13
The F-Droid part is a duplicate of #171

**Comment by jnnkB** [comment] 2021-05-29 12:38
fixed this for 1.4.3

**Closed by jnnkB** 2021-05-29 12:38 UTC
