### ISSUE TITLE
Open settings from keyboard

### ISSUE THREAD

**Issue by AlanSanchezP** [dslul/openboard#22] opened 2020-01-17 05:46 UTC
Currently it has the settings shortcut but when I try to use it nothing happens. (Using it on MIUI 11, android 9, redmi 6)

**Comment by dslul** [comment] 2020-01-17 14:37
You need to long-press the comma button, the other one is for changing keyboard, but I should add a little gear icon on top to avoid confusion.

**Comment by AlanSanchezP** [comment] 2020-01-17 19:02
I know, but when I tap "OpenBoard settings" the keyboard closes but nothing else happens.

**Comment by dslul** [comment] 2020-01-18 07:12
> I know, but when I tap "OpenBoard settings" the keyboard closes but nothing else happens.

That's strange, I can't reproduce this, what version do you have?

**Comment by AlanSanchezP** [comment] 2020-01-20 00:35
1.0 from f-droid

**Comment by Newbytee** [comment] 2020-01-20 16:30
I have a similar issue. However, in my case, I'm told that OpenBoard crashed. This is also with 1.0 from F-Droid, however on a HTC One M8s (not M8) running Android 6.0.

**Comment by dslul** [comment] 2020-01-21 19:49
Could you please post a stack trace? I don't know how to reproduce this, it doesn't happen on my phones (I tried both android 9 and 6)

**Comment by Newbytee** [comment] 2020-01-22 13:05
> Could you please post a stack trace? I don't know how to reproduce this, it doesn't happen on my phones (I tried both android 9 and 6)

Sure, however I'm not very familiar with Android development and debugging. Any pointers to how I would do this? Do I need to use adb?

**Comment by dslul** [comment] 2020-01-22 17:16
> Sure, however I'm not very familiar with Android development and debugging. Any pointers to how I would do this? Do I need to use adb?

Either with adb logcat, or with an app like syslog (I don't know if it works without root)

**Comment by Newbytee** [comment] 2020-01-23 11:23
I think this is it [logcat.txt](https://github.com/dslul/openboard/files/4102804/logcat.txt)

**Comment by dslul** [comment] 2020-01-23 14:53
Thanks, should be fixed now 067a8bf190cf6bc77fe3894192657c4fc33c7179

**Closed** 2020-01-27 22:19 UTC
Labels: bug
