### ISSUE TITLE
Clipboard (cut/copy/paste) functionality

### ISSUE THREAD

**Issue by MisterY** [dslul/openboard#60] opened 2020-02-08 11:20 UTC
Some keyboards offer the clipboard manipulation with cut/copy/pasting of the text. This is very useful in certain situation, like when working on in a terminal, where the system long-press is not possible.
Having an explicit option (menu/button/whatever) is much more preferable.

**Comment by ChildishGiant** [comment] 2020-02-08 19:01
Duplicate of #16

**Comment by MisterY** [comment] 2020-02-08 19:03
@ChildishGiant, I disagree. These are close but not the same as far as I can see. That request is very specific, with repro steps.
This is a generic cut/copy/paste functionality with dedicated buttons. At least that's how I see it.

**Comment by dslul** [comment] 2020-09-09 16:55
Related #84.

**Closed** 2022-01-16 09:10 UTC
