### ISSUE TITLE
Feature Request: Back space long press deletes whole word

### ISSUE THREAD

**Issue by utzer** [dslul/openboard#255] opened 2021-01-03 10:23 UTC
I would love a function that deletes a whole word when backspace is pressed for a longer duration, so the deletion should switch from letter wise to word wise.

**Comment by slaecker** [comment] 2021-01-04 08:43
I second that but configurable so it can be switched off by the user and the kick-in duration can also be set.

**Comment by jnnkB** [comment] 2021-03-16 16:38
This seems to be a duplicate of https://github.com/dslul/openboard/issues/28

**Closed** 2021-03-18 10:49 UTC
